"""
Configuration parameters for the simulation
"""

# Grass parameters
GRASS_SPREAD_CHANCE = 0.05
GRASS_ENERGY_VALUE = 20

# Herbivore parameters
HERBIVORE_INIT_ENERGY = 55
HERBIVORE_MAX_ENERGY = 110
HERBIVORE_HUNGER_LEVELS = [
    (20, 0.35),
    (10, 0.2),
    (0, 0.08)
]
HERBIVORE_ENERGY_LOSS_CHANCE = 0.2
HERBIVORE_BREEDING_ENERGY_THRESHOLD = 0.85
HERBIVORE_BREEDING_CHANCE = 0.15
HERBIVORE_BREEDING_ENERGY_COST = 0.45
HERBIVORE_OFFSPRING_ENERGY_FACTOR = 0.8

# Predator parameters
PREDATOR_INIT_ENERGY = 80
PREDATOR_MAX_ENERGY = 150
PREDATOR_HUNGER_LEVELS = [
    (15, 0.8),
    (7, 0.4),
    (0, 0.2)
]
PREDATOR_BREEDING_ENERGY_THRESHOLD = 0.9
PREDATOR_BREEDING_CHANCE = 0.05
PREDATOR_BREEDING_ENERGY_COST = 0.5
PREDATOR_OFFSPRING_ENERGY_FACTOR = 0.4
PREDATOR_BREEDING_COOLDOWN = 40
PREDATOR_PREY_ENERGY_VALUE = 30 